const path = require("path");

function toPosix(value) {
  return value.split(path.sep).join("/");
}

function findPresetOptions(siteConfig) {
  const presets = Array.isArray(siteConfig.presets) ? siteConfig.presets : [];
  for (const preset of presets) {
    if (!Array.isArray(preset)) {
      continue;
    }
    const [name, options] = preset;
    if (name === "@storybakery/docs-preset" && options && typeof options === "object") {
      return options;
    }
  }
  return {};
}

function resolveReferenceDirName(siteDir) {
  const siteConfig = require(path.join(siteDir, "docusaurus.config.js"));
  const presetOptions = findPresetOptions(siteConfig);

  const docsPath = (presetOptions.docs && presetOptions.docs.path) || "docs";
  const docsRootAbs = path.resolve(siteDir, docsPath);

  const referenceOptions = presetOptions.reference || {};
  const lang = referenceOptions.lang || "luau";

  const defaultOutDir = path.join(docsPath, "reference", lang);
  const outDirOption = referenceOptions.outDir || defaultOutDir;
  const outDirAbs = path.isAbsolute(outDirOption)
    ? outDirOption
    : path.resolve(siteDir, outDirOption);

  const relative = path.relative(docsRootAbs, outDirAbs);
  if (!relative || relative.startsWith("..")) {
    return toPosix(path.join("reference", lang));
  }
  return toPosix(relative);
}

const referenceDirName = resolveReferenceDirName(__dirname);

module.exports = {
  manual: [{ type: "doc", id: "index" }],
  reference: [{ type: "autogenerated", dirName: referenceDirName }],
};
