const path = require("path");

function toPosix(value) {
    return value.split(path.sep).join("/");
}

function findPresetOptions(siteConfig) {
    const presets = Array.isArray(siteConfig.presets) ? siteConfig.presets : [];
    for (const preset of presets) {
        if (!Array.isArray(preset)) {
            continue;
        }
        const [name, options] = preset;
        if (name === "@storybakery/docs-preset" && options && typeof options === "object") {
            return options;
        }
    }
    return {};
}

// Docusaurus 3 환경에서는 docusaurus.config.js를 require 할 경우 순환 참조로 인해
// module.exports가 빈 객체로 로드될 수 있습니다. 
// 테스트 프로젝트이므로 기본 경로를 직접 지정합니다.
const referenceDirName = "reference/luau";

module.exports = {
    manual: [
        { type: "doc", id: "index" },
        { type: "doc", id: "bakerywave-flow" },
        { type: "doc", id: "luau-links" },
        { type: "doc", id: "luau-tags-test" },
    ],
    reference: [{ type: "autogenerated", dirName: referenceDirName }],
};
