export default {
  manual: [
    { type: "doc", id: "index" },
    { type: "doc", id: "bakerywave" },
    { type: "doc", id: "bakerywave-config" },
    { type: "doc", id: "luau-tags" },
    { type: "doc", id: "luau-types" },
  ],
  reference: [{ type: "autogenerated", dirName: "reference" }],
};
