export default {
    manual: [
        {
            type: "category",
            label: "소개",
            collapsed: false,
            items: [
                "intro/what-is-bakerywave",
                "intro/installation",
            ],
        },
        {
            type: "category",
            label: "튜토리얼",
            collapsed: false,
            items: [
                "tutorial/create-site",
                "tutorial/run-server",
                "tutorial/write-manual",
                "tutorial/luau-api",
            ],
        },
        {
            type: "category",
            label: "가이드",
            items: [
                "guides/configuration",
                "guides/cli",
                "guides/customization",
                "guides/deployment",
            ],
        },
        {
            type: "category",
            label: "Luau 문서화",
            items: [
                "luau-tags/overview",
                "luau-tags/supported-tags",
                "luau-tags/docgen-scripts",
                "luau-tags/best-practices",
            ],
        },
        {
            type: "category",
            label: "개발 기여",
            items: [
                { type: "autogenerated", dirName: "development" },
            ],
        },
    ],
    reference: [{ type: "autogenerated", dirName: "reference" }],
};
